FROM openjdk:8u131-jdk-alpine
    VOLUME /src
    ADD helper/java/includes /includes
    ADD saved_test/TP2-101/TestRunner.java /includes/TestRunner.java
    WORKDIR /src
    ENTRYPOINT javac -cp /includes/junit-4.13-beta-1.jar:/includes/hamcrest-all-1.3.jar:. MaClasseTest.java /includes/TestRunner.java -d . && java -cp /includes/hamcrest-all-1.3.jar:/includes/junit-4.13-beta-1.jar:. TestRunner
